Assignment answers
Code-the-Dream-School/section-4-playing-in-the-dom-elizabethompson pull request #2
Opened 2020-07-14 01:50 UTC by elizabethompson

2020-07-15 18:00 UTC, sinancengiz commented on index.js
> +div1.onclick = function () {
your code for this question perfectly works only thing I can add is that you can set inner Html to X at the beginning then it can start with showing X instead of starting with empty square

2020-07-15 18:01 UTC, sinancengiz commented on index.js
> -
your code for this question perfectly works only thing I can add is that you can set inner Html to X at the beginning then it can start with showing X instead of starting with empty square

2020-07-15 18:08 UTC, sinancengiz commented on index.js
> -
in line 19 const colors already been declared and it declared again at line 23. one of them should be removed to not to get Uncaught SyntaxError.

2020-07-15 18:44 UTC, sinancengiz commented on index.js
> -
calculate_sphere function at line 38 is empty, then calculateSphere function at line 51 is used. when we remove first calculate function at line 38 we get Uncaught ReferenceError: calculate_sphere . We can comment or remove line 45 window.onload at because it is also not used.Then the code runs smoothly

2020-07-15 19:04 UTC, sinancengiz commented on index.js
> +
Lines 78 91 and 104 tempbutton is not defined , we can append button1, button2 and button3.  Also in question it is asked to hide all question with answer. We can   get element by question id for example in line 105 document.getElementById("question_1") to hide all question with answer. Other then that great job

2020-07-15 19:35 UTC, sinancengiz requested changes
Hi Elizabeth, 

Really great job so far, I put some comments for some changes, 
When changes done I can go over it again.

Best,

Sinan

2020-08-17 21:42 UTC, elizabethompson commented
No longer using this PR as a "Code Review Exercise", going to merge and close.

2020-08-17 21:42 UTC, merged